apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spring-petclinic-app
  namespace: openshift-gitops
spec:
  destination:
    namespace:
    server: https://kubernetes.default.svc  
  project: av-dso-poc
  source:
    path: openshift
    repoURL: 'https://github.com/avtarm/spring-petclinic.git'
    targetRevision: main  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    # syncOptions:
    # - CreateNamespace=true
  # ignoreDifferences:
  #   - kind: ServiceAccount
  #     jsonPointers:
  #     - /secrets
  #     - /imagePullSecrets